<?php

namespace Database\Seeders;

use App\Models\Indikator;
use App\Models\Subsidebar;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class IndikatorSeeder extends Seeder
{
    /**
     * Master daftar indikator (definisi tabel), hasil pemetaan dari daftar file Excel BPS
     * yang tersedia di menu Data Makro. Seeder ini HANYA membuat definisi indikatornya
     * (judul, slug, subsidebar, tipe_baris, nama_file_asli untuk auto-match saat upload).
     * Data nilainya sendiri diisi lewat proses upload/import Excel (IndikatorExcelImporter),
     * bukan lewat seeder ini.
     *
     * nama_file_asli sengaja disalin persis apa adanya (termasuk typo/spasi ganda pada nama
     * file sumber) supaya fitur auto-match nama file saat upload bisa bekerja akurat.
     */
    public function run(): void
    {
        $data = [
            [
                'subsidebar' => 'KEPENDUDUKAN DAN MIGRASI',
                'nama_judul' => 'Jumlah Penduduk Kelompok Umur Jenis Kelamin',
                'slug' => 'jumlah-penduduk-kelompok-umur-jenis-kelamin',
                'tipe_baris' => 'kelompok_umur',
                'nama_file_asli' => 'Jumlah Penduduk Kelompok Umur Jenis Kelamin 2025.xls',
            ],
            [
                'subsidebar' => 'KEPENDUDUKAN DAN MIGRASI',
                'nama_judul' => 'Jumlah Penduduk Menurut Agama dan Kecamatan di Kabupaten Sukabumi',
                'slug' => 'jumlah-penduduk-menurut-agama-dan-kecamatan-di-kabupaten-sukabumi',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Penduduk Menurut Agama dan Kecamatan di Kabupaten Sukabumi2025.xls',
            ],
            [
                'subsidebar' => 'KEPENDUDUKAN DAN MIGRASI',
                'nama_judul' => 'Jumlah Penduduk Menurut Kecamatan',
                'slug' => 'jumlah-penduduk-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Penduduk Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'KEPENDUDUKAN DAN MIGRASI',
                'nama_judul' => 'Kepadatan Penduduk Menurut Kecamatan',
                'slug' => 'kepadatan-penduduk-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Kepadatan Penduduk Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'KEPENDUDUKAN DAN MIGRASI',
                'nama_judul' => 'Laju Pertumbuhan Penduduk Menurut Kecamatan',
                'slug' => 'laju-pertumbuhan-penduduk-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Laju Pertumbuhan Penduduk Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'KEPENDUDUKAN DAN MIGRASI',
                'nama_judul' => 'Persentase Ruta menurut jenis jaminan sosial yang diterima di kabupaten sukabumi',
                'slug' => 'persentase-ruta-menurut-jenis-jaminan-sosial-yang-diterima-di-kabupaten-sukabumi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Persentase Ruta menurut jenis jaminan sosial yang diterima di kabupaten sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'KEPENDUDUKAN DAN MIGRASI',
                'nama_judul' => 'Persentase Ruta menurut jenis program perlindungan sosial yang diterima di kabupaten sukabumi',
                'slug' => 'persentase-ruta-menurut-jenis-program-perlindungan-sosial-yang-diterima-di-kabupaten-sukabumi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Persentase Ruta menurut jenis program perlindungan sosial yang diterima di kabupaten sukabumi2025.xls',
            ],
            [
                'subsidebar' => 'KEPENDUDUKAN DAN MIGRASI',
                'nama_judul' => 'Rasio jenis Kelamin Penduduk Menurut Kecamatan',
                'slug' => 'rasio-jenis-kelamin-penduduk-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Rasio jenis Kelamin Penduduk Menurut Kecamatan 2025..xls',
            ],
            [
                'subsidebar' => 'KESEHATAN',
                'nama_judul' => 'Jumlah Sarana Kesehatan menurut Kecamatan',
                'slug' => 'jumlah-sarana-kesehatan-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Sarana Kesehatan menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'KESEHATAN',
                'nama_judul' => 'Jumlah tenaga Kesehatan menurut Kecamatan',
                'slug' => 'jumlah-tenaga-kesehatan-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah tenaga Kesehatan menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'KONSUMSI DAN PENDAPATAN',
                'nama_judul' => 'Rata rata pengeluaran sebulan komoditas makanan Kab Sukabumi',
                'slug' => 'rata-rata-pengeluaran-sebulan-komoditas-makanan-kab-sukabumi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Rata rata pengeluaran sebulan komoditas makanan Kab Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'KONSUMSI DAN PENDAPATAN',
                'nama_judul' => 'Rata rata pengeluaran sebulan komoditas non makanan Kab Sukabumi',
                'slug' => 'rata-rata-pengeluaran-sebulan-komoditas-non-makanan-kab-sukabumi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Rata rata pengeluaran sebulan komoditas non makanan Kab Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'SOSIAL BUDAYA',
                'nama_judul' => 'Jumlah Tempat Peribadatan Menurut Kecamatan di Kabupaten Sukabumi',
                'slug' => 'jumlah-tempat-peribadatan-menurut-kecamatan-di-kabupaten-sukabumi',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Tempat Peribadatan Menurut Kecamatan di Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'TENAGA KERJA',
                'nama_judul' => 'TPAK Menurut KabKota Jenis Kelamin',
                'slug' => 'tpak-menurut-kabkota-jenis-kelamin',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'TPAK Menurut KabKota Jenis Kelamin 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Guru MA Menurut Kecamatan',
                'slug' => 'jumlah-guru-ma-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Guru MA Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Guru MI Menurut Kecamatan',
                'slug' => 'jumlah-guru-mi-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Guru MI Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Guru MTS Menurut Kecamatan',
                'slug' => 'jumlah-guru-mts-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Guru MTS Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Guru SD Menurut Kecamatan',
                'slug' => 'jumlah-guru-sd-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Guru SD Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Guru SMA Menurut Kecamatan',
                'slug' => 'jumlah-guru-sma-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Guru SMA Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Guru SMK Menurut Kecamatan',
                'slug' => 'jumlah-guru-smk-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Guru SMK Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Guru SMP Menurut Kecamatan',
                'slug' => 'jumlah-guru-smp-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Guru SMP Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Guru TK Menurut Kecamatan',
                'slug' => 'jumlah-guru-tk-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Guru TK Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Sekolah MA Menurut Kecamatan',
                'slug' => 'jumlah-sekolah-ma-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Sekolah MA Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Sekolah MI Menurut Kecamatan',
                'slug' => 'jumlah-sekolah-mi-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Sekolah MI Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Sekolah MTS Menurut Kecamatan',
                'slug' => 'jumlah-sekolah-mts-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Sekolah MTS Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Sekolah SD Menurut Kecamatan',
                'slug' => 'jumlah-sekolah-sd-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Sekolah SD Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Sekolah SMA Menurut Kecamatan',
                'slug' => 'jumlah-sekolah-sma-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Sekolah SMA Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Sekolah SMK Menurut Kecamatan',
                'slug' => 'jumlah-sekolah-smk-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Sekolah SMK Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Sekolah SMP Menurut Kecamatan',
                'slug' => 'jumlah-sekolah-smp-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Sekolah SMP Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah TK Menurut Kecamatan',
                'slug' => 'jumlah-tk-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah TK Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'INDEKS PEMBANGUNAN MANUSIA',
                'nama_judul' => 'Indeks Pembangunan Manusia (IPM) Menurut Jenis Kelamin Kabupaten Kota (Umur Harapan HidupUHH Hasil LF SP2020)',
                'slug' => 'indeks-pembangunan-manusia-ipm-menurut-jenis-kelamin-kabupaten-kota-umur-harapan-hidupuhh-hasil-lf-sp2020',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Indeks Pembangunan Manusia (IPM) Menurut Jenis Kelamin Kabupaten Kota (Umur Harapan HidupUHH Hasil LF SP2020) 2025.xls',
            ],
            [
                'subsidebar' => 'INDEKS PEMBANGUNAN MANUSIA',
                'nama_judul' => 'Indeks Pembangunan Manusia (IPM) Menurut Kabupaten Kota (Umur Harapan HidupUHH Hasil LF SP2020)',
                'slug' => 'indeks-pembangunan-manusia-ipm-menurut-kabupaten-kota-umur-harapan-hidupuhh-hasil-lf-sp2020',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Indeks Pembangunan Manusia (IPM) Menurut Kabupaten Kota (Umur Harapan HidupUHH Hasil LF SP2020) 2025.xls',
            ],
            [
                'subsidebar' => 'KEMISKINAN',
                'nama_judul' => 'Garis Kemiskinan KabupatenKota Provinsi Jawa Barat',
                'slug' => 'garis-kemiskinan-kabupatenkota-provinsi-jawa-barat',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Garis Kemiskinan KabupatenKota Provinsi Jawa Barat 2025 (1).xls',
            ],
            [
                'subsidebar' => 'KEMISKINAN',
                'nama_judul' => 'Indeks kedalaman kemiskinan kabkota',
                'slug' => 'indeks-kedalaman-kemiskinan-kabkota',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Indeks kedalaman kemiskinan kabkota 2025.xls',
            ],
            [
                'subsidebar' => 'KEMISKINAN',
                'nama_judul' => 'Indeks keparahan kemiskinan kabkota',
                'slug' => 'indeks-keparahan-kemiskinan-kabkota',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Indeks keparahan kemiskinan kabkota 2025.xls',
            ],
            [
                'subsidebar' => 'KEMISKINAN',
                'nama_judul' => 'Jumlah Penduduk Miskin kabkota',
                'slug' => 'jumlah-penduduk-miskin-kabkota',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Jumlah Penduduk Miskin kabkota 2025.xls',
            ],
            [
                'subsidebar' => 'KEMISKINAN',
                'nama_judul' => 'Persentase Penduduk Miskin kabkota',
                'slug' => 'persentase-penduduk-miskin-kabkota',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Persentase Penduduk Miskin kabkota 2025.xls',
            ],
            [
                'subsidebar' => 'PEMERINTAHAN',
                'nama_judul' => 'Jumlah Desa Kelurahan Menurut Kecamatan',
                'slug' => 'jumlah-desa-kelurahan-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Desa Kelurahan Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PEMERINTAHAN',
                'nama_judul' => 'Realisasi Belanja Pemerintah Kabupaten Sukabumi Menurut Jenis Belanja',
                'slug' => 'realisasi-belanja-pemerintah-kabupaten-sukabumi-menurut-jenis-belanja',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Realisasi Belanja Pemerintah Kabupaten Sukabumi Menurut Jenis Belanja 2025.xls',
            ],
            [
                'subsidebar' => 'PEMERINTAHAN',
                'nama_judul' => 'Realisasi Pendapatan Pemerintah Kabupaten Sukabumi Menurut Jenis Pendapatan',
                'slug' => 'realisasi-pendapatan-pemerintah-kabupaten-sukabumi-menurut-jenis-pendapatan',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Realisasi Pendapatan Pemerintah Kabupaten Sukabumi Menurut Jenis Pendapatan 2025.xls',
            ],
            [
                'subsidebar' => 'PEMUKIMAN DAN PERUMAHAN',
                'nama_judul' => 'Persentase Rumah Tangga Menurut Karakteristik dan Bahan Bangunan Utama Atap Rumah Terluas',
                'slug' => 'persentase-rumah-tangga-menurut-karakteristik-dan-bahan-bangunan-utama-atap-rumah-terluas',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Persentase Rumah Tangga Menurut Karakteristik dan Bahan Bangunan Utama Atap Rumah Terluas 2025.xls',
            ],
            [
                'subsidebar' => 'PEMUKIMAN DAN PERUMAHAN',
                'nama_judul' => 'Persentase Rumah Tangga Menurut Karakteristik dan Bahan Bangunan Utama Dinding Rumah Terluas',
                'slug' => 'persentase-rumah-tangga-menurut-karakteristik-dan-bahan-bangunan-utama-dinding-rumah-terluas',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Persentase Rumah Tangga Menurut Karakteristik dan Bahan Bangunan Utama Dinding Rumah Terluas 2025.xls',
            ],
            [
                'subsidebar' => 'PEMUKIMAN DAN PERUMAHAN',
                'nama_judul' => 'Persentase Rumah Tangga Menurut Karakteristik dan Bahan Bangunan Utama Lantai Rumah Terluas',
                'slug' => 'persentase-rumah-tangga-menurut-karakteristik-dan-bahan-bangunan-utama-lantai-rumah-terluas',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Persentase Rumah Tangga Menurut Karakteristik dan Bahan Bangunan Utama Lantai Rumah Terluas 2025.xls',
            ],
            [
                'subsidebar' => 'PEMUKIMAN DAN PERUMAHAN',
                'nama_judul' => 'Persentase Rumah Tangga Menurut Karakteristik dan status kepemilikan bangunan tempat tinggal',
                'slug' => 'persentase-rumah-tangga-menurut-karakteristik-dan-status-kepemilikan-bangunan-tempat-tinggal',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Persentase Rumah Tangga Menurut Karakteristik dan status kepemilikan bangunan tempat tinggal 2025.xls',
            ],
            [
                'subsidebar' => 'PEMUKIMAN DAN PERUMAHAN',
                'nama_judul' => 'Persentase Rumah Tangga Menurut Karakteristik dan status kepemilikan dan penggunaan fasilitas tempat buang air besar',
                'slug' => 'persentase-rumah-tangga-menurut-karakteristik-dan-status-kepemilikan-dan-penggunaan-fasilitas-tempat-buang-air-besar',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Persentase Rumah Tangga Menurut Karakteristik dan status kepemilikan dan penggunaan fasilitas tempat buang air besar 2025 .xls',
            ],
            [
                'subsidebar' => 'POLITIK DAN KEAMANAN',
                'nama_judul' => 'Jumlah Anggota Dewan Perwakilan Rakyat Daerah Menurut Partai Politik dan Jenis Kelamin',
                'slug' => 'jumlah-anggota-dewan-perwakilan-rakyat-daerah-menurut-partai-politik-dan-jenis-kelamin',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Jumlah Anggota Dewan Perwakilan Rakyat Daerah Menurut Partai Politik dan Jenis Kelamin 2025.xls',
            ],
            [
                'subsidebar' => 'ENERGI',
                'nama_judul' => 'Daya Terpasang, Produksi dan Distribusi Listrik PT. PLN di Kabupaten Sukabumi',
                'slug' => 'daya-terpasang-produksi-dan-distribusi-listrik-pt-pln-di-kabupaten-sukabumi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Daya Terpasang, Produksi dan Distribusi Listrik PT. PLN di Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'ENERGI',
                'nama_judul' => 'Jumlah Distribusi Air Bersih per Bulan di Kabupaten Sukabumi',
                'slug' => 'jumlah-distribusi-air-bersih-per-bulan-di-kabupaten-sukabumi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Jumlah Distribusi Air Bersih per Bulan di Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'ENERGI',
                'nama_judul' => 'Jumlah Pelanggan Listrik Menurut Kecamatan di Kabupaten Sukabumi',
                'slug' => 'jumlah-pelanggan-listrik-menurut-kecamatan-di-kabupaten-sukabumi',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Pelanggan Listrik Menurut Kecamatan di Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'ENERGI',
                'nama_judul' => 'Jumlah Pelanggan dan Air yang Disalurkan Menurut Kecamatan',
                'slug' => 'jumlah-pelanggan-dan-air-yang-disalurkan-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Pelanggan dan Air yang Disalurkan Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'GEOGRAFI',
                'nama_judul' => 'Jarak ke Ibukota Kabupaten Menurut Kecamatan di Kabupaten Sukabumi',
                'slug' => 'jarak-ke-ibukota-kabupaten-menurut-kecamatan-di-kabupaten-sukabumi',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jarak ke Ibukota Kabupaten  Menurut Kecamatan di Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'GEOGRAFI',
                'nama_judul' => 'Luas WIlayah Menurut Kecamatan di Kabupaten Sukabumi',
                'slug' => 'luas-wilayah-menurut-kecamatan-di-kabupaten-sukabumi',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Luas WIlayah Menurut Kecamatan di Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'IKLIM ATAU LINGKUNGAN',
                'nama_judul' => 'Jumlah Curah Hujan Menurut Bulan di Stasiun Geofisika Palabuhanratu, Badan Meteorologi, Klimatologi dan Geofisika (BMKG) Stasiun Klimatologi Jawa Barat (Hari)',
                'slug' => 'jumlah-curah-hujan-menurut-bulan-di-stasiun-geofisika-palabuhanratu-badan-meteorologi-klimatologi-dan-geofisika-bmkg-stasiun-klimatologi-jawa-barat-hari',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Jumlah Curah  Hujan Menurut Bulan di Stasiun Geofisika Palabuhanratu, Badan Meteorologi, Klimatologi dan Geofisika (BMKG) Stasiun Klimatologi Jawa Barat (Hari) 2025.xls',
            ],
            [
                'subsidebar' => 'IKLIM ATAU LINGKUNGAN',
                'nama_judul' => 'Jumlah Hari Hujan Menurut Bulan di Stasiun Geofisika Palabuhanratu, Badan Meteorologi, Klimatologi dan Geofisika (BMKG) Stasiun Klimatologi Jawa Barat (Hari)',
                'slug' => 'jumlah-hari-hujan-menurut-bulan-di-stasiun-geofisika-palabuhanratu-badan-meteorologi-klimatologi-dan-geofisika-bmkg-stasiun-klimatologi-jawa-barat-hari',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Jumlah Hari Hujan Menurut Bulan di Stasiun Geofisika Palabuhanratu, Badan Meteorologi, Klimatologi dan Geofisika (BMKG) Stasiun Klimatologi Jawa Barat (Hari) 2025.xls',
            ],
            [
                'subsidebar' => 'IKLIM ATAU LINGKUNGAN',
                'nama_judul' => 'Jumlah Jam Penyinaran Menurut Bulan di Stasiun Geofisika Palabuhanratu, Badan Meteorologi, Klimatologi dan Geofisika (BMKG) Stasiun Klimatologi Jawa Barat (Hari)',
                'slug' => 'jumlah-jam-penyinaran-menurut-bulan-di-stasiun-geofisika-palabuhanratu-badan-meteorologi-klimatologi-dan-geofisika-bmkg-stasiun-klimatologi-jawa-barat-hari',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Jumlah Jam Penyinaran Menurut Bulan di Stasiun Geofisika Palabuhanratu, Badan Meteorologi, Klimatologi dan Geofisika (BMKG) Stasiun Klimatologi Jawa Barat (Hari) 2025.xls',
            ],
            [
                'subsidebar' => 'KEUANGAN',
                'nama_judul' => 'Jumlah Koperasi Menurut Jenis Koperasi dan Kecamatan',
                'slug' => 'jumlah-koperasi-menurut-jenis-koperasi-dan-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Koperasi  Menurut Jenis Koperasi dan Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'KEUANGAN',
                'nama_judul' => 'Jumlah Koperasi yang aktif Menurut Kecamatan',
                'slug' => 'jumlah-koperasi-yang-aktif-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Koperasi yang aktif Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'NERACA SOSIAL EKONOMI',
                'nama_judul' => 'Jumlah Minimarket Menurut Kecamatan di Kabupaten Sukabumi',
                'slug' => 'jumlah-minimarket-menurut-kecamatan-di-kabupaten-sukabumi',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Minimarket Menurut Kecamatan di Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'NERACA SOSIAL EKONOMI',
                'nama_judul' => 'Jumlah Sarana Perdagangan Menurut Jenisnya di Kabupaten Sukabumi',
                'slug' => 'jumlah-sarana-perdagangan-menurut-jenisnya-di-kabupaten-sukabumi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Jumlah Sarana Perdagangan Menurut Jenisnya di Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'PARIWISATA',
                'nama_judul' => 'Jumlah Akomodasi Menurut Klasifikasinya di Kabupaten Sukabumi',
                'slug' => 'jumlah-akomodasi-menurut-klasifikasinya-di-kabupaten-sukabumi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Jumlah Akomodasi Menurut Klasifikasinya di Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'PARIWISATA',
                'nama_judul' => 'Jumlah Kamar Menurut Klasifikasi Akomodasi di Kabupaten Sukabumi',
                'slug' => 'jumlah-kamar-menurut-klasifikasi-akomodasi-di-kabupaten-sukabumi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Jumlah Kamar Menurut Klasifikasi Akomodasi di Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'PARIWISATA',
                'nama_judul' => 'Jumlah Tempat Tidur Menurut Klasifikasi Akomodasi di Kabupaten Sukabumi',
                'slug' => 'jumlah-tempat-tidur-menurut-klasifikasi-akomodasi-di-kabupaten-sukabumi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Jumlah Tempat Tidur Menurut Klasifikasi Akomodasi di Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'TRANSPORTASI',
                'nama_judul' => 'Panjang Jalan menurut Jenis permukaan jalan',
                'slug' => 'panjang-jalan-menurut-jenis-permukaan-jalan',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Panjang Jalan menurut Jenis permukaan jalan 2025.xls',
            ],
            [
                'subsidebar' => 'TRANSPORTASI',
                'nama_judul' => 'Panjang Jalan menurut Kondisi jalan',
                'slug' => 'panjang-jalan-menurut-kondisi-jalan',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Panjang Jalan menurut Kondisi jalan 2025.xls',
            ],
            [
                'subsidebar' => 'TRANSPORTASI',
                'nama_judul' => 'Panjang Jalan menurut Tingkat Kewenangan Pemerintah',
                'slug' => 'panjang-jalan-menurut-tingkat-kewenangan-pemerintah',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Panjang Jalan menurut Tingkat Kewenangan Pemerintah 2025.xls',
            ],
            [
                'subsidebar' => 'INDUSTRI',
                'nama_judul' => 'Banyaknya Usaha Mikro Kecil Menurut Kab Kota di Jawa BArat',
                'slug' => 'banyaknya-usaha-mikro-kecil-menurut-kab-kota-di-jawa-barat',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Banyaknya Usaha Mikro Kecil Menurut Kab Kota di Jawa BArat 2025.xls',
            ],
            [
                'subsidebar' => 'INDUSTRI',
                'nama_judul' => 'Jumlah Kantor Pos pembantu Menurut Kecamatan di kab sukabumi',
                'slug' => 'jumlah-kantor-pos-pembantu-menurut-kecamatan-di-kab-sukabumi',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Kantor Pos pembantu Menurut Kecamatan di kab sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'KOMUNIKASI',
                'nama_judul' => 'Jumlah Kantor Pos pembantu Menurut Kecamatan di kab sukabumi',
                'slug' => 'jumlah-kantor-pos-pembantu-menurut-kecamatan-di-kab-sukabumi-komunikasi',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Kantor Pos pembantu Menurut Kecamatan di kab sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'KOMUNIKASI',
                'nama_judul' => 'Persentase Penduduk Berumur 5 Tahun ke Atas Menurut Karakteristik dan Penggunaan Internet',
                'slug' => 'persentase-penduduk-berumur-5-tahun-ke-atas-menurut-karakteristik-dan-penggunaan-internet',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Persentase Penduduk Berumur 5 Tahun ke Atas Menurut Karakteristik dan Penggunaan Internet 2025.xls',
            ],
            [
                'subsidebar' => 'KOMUNIKASI',
                'nama_judul' => 'Persentase Penduduk Berumur 5 Tahun ke Atas Menurut Karakteristik dan Penggunaan Teknologi Informasi',
                'slug' => 'persentase-penduduk-berumur-5-tahun-ke-atas-menurut-karakteristik-dan-penggunaan-teknologi-informasi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Persentase Penduduk Berumur 5 Tahun ke Atas Menurut Karakteristik dan Penggunaan Teknologi Informasi 2025.xls',
            ],
            [
                'subsidebar' => 'PERIKANAN',
                'nama_judul' => 'Nilai Produksi Ikan yang Didaratkan per Bulan di Pelabuhan Nusantara Palabuhanratu (rupiah)',
                'slug' => 'nilai-produksi-ikan-yang-didaratkan-per-bulan-di-pelabuhan-nusantara-palabuhanratu-rupiah',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Nilai Produksi Ikan yang Didaratkan per Bulan di Pelabuhan Nusantara Palabuhanratu (rupiah) 2025.xls',
            ],
            [
                'subsidebar' => 'PERIKANAN',
                'nama_judul' => 'Produksi Ikan yang Didaratkan per Bulan di Pelabuhan Nusantara Palabuhanratu (kg)',
                'slug' => 'produksi-ikan-yang-didaratkan-per-bulan-di-pelabuhan-nusantara-palabuhanratu-kg',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Produksi Ikan yang Didaratkan per Bulan di Pelabuhan Nusantara Palabuhanratu (kg) 2025.xls',
            ],
            [
                'subsidebar' => 'TANAMAN PANGAN',
                'nama_judul' => 'Luas Panen (ha), Produktivitas (kuha), Produksi (ton) Jagung Menurut Kecamatan Kabupaten Sukabumi',
                'slug' => 'luas-panen-ha-produktivitas-kuha-produksi-ton-jagung-menurut-kecamatan-kabupaten-sukabumi',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Luas Panen (ha), Produktivitas (kuha), Produksi (ton) Jagung Menurut Kecamatan Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'TANAMAN PANGAN',
                'nama_judul' => 'Luas Panen (ha), Produktivitas (kuha), Produksi (ton) Kacang Hijau Menurut Kecamatan Kabupaten Sukabumi',
                'slug' => 'luas-panen-ha-produktivitas-kuha-produksi-ton-kacang-hijau-menurut-kecamatan-kabupaten-sukabumi',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Luas Panen (ha), Produktivitas (kuha), Produksi (ton) Kacang Hijau Menurut Kecamatan Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'TANAMAN PANGAN',
                'nama_judul' => 'Luas Panen (ha), Produktivitas (kuha), Produksi (ton) Kacang Kedelai Menurut Kecamatan Kabupaten Sukabumi',
                'slug' => 'luas-panen-ha-produktivitas-kuha-produksi-ton-kacang-kedelai-menurut-kecamatan-kabupaten-sukabumi',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Luas Panen (ha), Produktivitas (kuha), Produksi (ton) Kacang Kedelai Menurut Kecamatan Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'TANAMAN PANGAN',
                'nama_judul' => 'Luas Panen (ha), Produktivitas (kuha), Produksi (ton) Kacang Tanah Menurut Kecamatan Kabupaten Sukabumi',
                'slug' => 'luas-panen-ha-produktivitas-kuha-produksi-ton-kacang-tanah-menurut-kecamatan-kabupaten-sukabumi',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Luas Panen (ha), Produktivitas (kuha), Produksi (ton) Kacang Tanah Menurut Kecamatan Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'TANAMAN PANGAN',
                'nama_judul' => 'Luas Panen (ha), Produktivitas (kuha), Produksi (ton) Padi Gogo Menurut Kecamatan Kabupaten Sukabumi',
                'slug' => 'luas-panen-ha-produktivitas-kuha-produksi-ton-padi-gogo-menurut-kecamatan-kabupaten-sukabumi',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Luas Panen (ha), Produktivitas (kuha), Produksi (ton) Padi Gogo Menurut Kecamatan Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'TANAMAN PANGAN',
                'nama_judul' => 'Luas Panen (ha), Produktivitas (kuha), Produksi (ton) Padi Sawah Menurut Kecamatan Kabupaten Sukabumi',
                'slug' => 'luas-panen-ha-produktivitas-kuha-produksi-ton-padi-sawah-menurut-kecamatan-kabupaten-sukabumi',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Luas Panen (ha), Produktivitas (kuha), Produksi (ton) Padi Sawah Menurut Kecamatan Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'TANAMAN PANGAN',
                'nama_judul' => 'Luas Panen (ha), Produktivitas (kuha), Produksi (ton) Ubi Jalar Menurut Kecamatan Kabupaten Sukabumi',
                'slug' => 'luas-panen-ha-produktivitas-kuha-produksi-ton-ubi-jalar-menurut-kecamatan-kabupaten-sukabumi',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Luas Panen (ha), Produktivitas (kuha), Produksi (ton) Ubi Jalar Menurut Kecamatan Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'TANAMAN PANGAN',
                'nama_judul' => 'Luas Panen (ha), Produktivitas (kuha), Produksi (ton) Ubi Kayu Menurut Kecamatan Kabupaten Sukabumi',
                'slug' => 'luas-panen-ha-produktivitas-kuha-produksi-ton-ubi-kayu-menurut-kecamatan-kabupaten-sukabumi',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Luas Panen (ha), Produktivitas (kuha), Produksi (ton) Ubi Kayu Menurut Kecamatan Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'HOLTIKULTURA',
                'nama_judul' => 'Luas Panen Tanaman Biofarmaka Semusim Menurut Jenis Tanaman di Kabupaten Sukabumi',
                'slug' => 'luas-panen-tanaman-biofarmaka-semusim-menurut-jenis-tanaman-di-kabupaten-sukabumi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Luas Panen Tanaman Biofarmaka Semusim Menurut Jenis Tanaman di Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'HOLTIKULTURA',
                'nama_judul' => 'Luas Panen Tanaman Hias Semusim Menurut Jenis Tanaman di Kabupaten Sukabumi',
                'slug' => 'luas-panen-tanaman-hias-semusim-menurut-jenis-tanaman-di-kabupaten-sukabumi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Luas Panen Tanaman Hias Semusim Menurut Jenis Tanaman di Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'HOLTIKULTURA',
                'nama_judul' => 'Luas Panen Tanaman Sayuran dan Buah-buahan Semusim Menurut Jenis Tanaman di Kabupaten Sukabumi',
                'slug' => 'luas-panen-tanaman-sayuran-dan-buah-buahan-semusim-menurut-jenis-tanaman-di-kabupaten-sukabumi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Luas Panen Tanaman Sayuran dan Buah-buahan Semusim Menurut Jenis Tanaman di Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'HOLTIKULTURA',
                'nama_judul' => 'Produksi Tanaman Biofarmaka Semusim Menurut Jenis Tanaman di Kabupaten Sukabumi',
                'slug' => 'produksi-tanaman-biofarmaka-semusim-menurut-jenis-tanaman-di-kabupaten-sukabumi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Produksi Tanaman Biofarmaka Semusim Menurut Jenis Tanaman di Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'HOLTIKULTURA',
                'nama_judul' => 'Produksi Tanaman Buah buahan dan Sayuran Tahunan Menurut Jenis Tanaman di Kabupaten Sukabumi',
                'slug' => 'produksi-tanaman-buah-buahan-dan-sayuran-tahunan-menurut-jenis-tanaman-di-kabupaten-sukabumi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Produksi Tanaman Buah buahan dan Sayuran Tahunan Menurut Jenis Tanaman di Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'HOLTIKULTURA',
                'nama_judul' => 'Produksi Tanaman Hias Semusim Menurut Jenis Tanaman di Kabupaten Sukabumi',
                'slug' => 'produksi-tanaman-hias-semusim-menurut-jenis-tanaman-di-kabupaten-sukabumi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Produksi Tanaman Hias Semusim Menurut Jenis Tanaman di Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'HOLTIKULTURA',
                'nama_judul' => 'Produksi Tanaman Sayuran dan Buah-buahan Semusim Menurut Jenis Tanaman di Kabupaten Sukabumi',
                'slug' => 'produksi-tanaman-sayuran-dan-buah-buahan-semusim-menurut-jenis-tanaman-di-kabupaten-sukabumi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Produksi Tanaman Sayuran dan Buah-buahan Semusim Menurut Jenis Tanaman di Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Murid MA Menurut Kecamatan',
                'slug' => 'jumlah-murid-ma-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Murid MA Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Murid MI Menurut Kecamatan',
                'slug' => 'jumlah-murid-mi-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Murid MI Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Murid MTS Menurut Kecamatan',
                'slug' => 'jumlah-murid-mts-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Murid MTS Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Murid SD Menurut Kecamatan',
                'slug' => 'jumlah-murid-sd-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Murid SD Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Murid SMA Menurut Kecamatan',
                'slug' => 'jumlah-murid-sma-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Murid SMA Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Murid SMK Menurut Kecamatan',
                'slug' => 'jumlah-murid-smk-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Murid SMK Menurut Kecamatan 20255.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Murid SMP Menurut Kecamatan',
                'slug' => 'jumlah-murid-smp-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Murid SMP Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PENDIDIKAN',
                'nama_judul' => 'Jumlah Murid TK Menurut Kecamatan',
                'slug' => 'jumlah-murid-tk-menurut-kecamatan',
                'tipe_baris' => 'kecamatan',
                'nama_file_asli' => 'Jumlah Murid TK Menurut Kecamatan 2025.xls',
            ],
            [
                'subsidebar' => 'PERKEBUNAN',
                'nama_judul' => 'Luas Areal Tanaman Perkebunan Rakyat Menurut Jenis Tanaman Perkebunan',
                'slug' => 'luas-areal-tanaman-perkebunan-rakyat-menurut-jenis-tanaman-perkebunan',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Luas Areal Tanaman Perkebunan Rakyat Menurut Jenis Tanaman Perkebunan 2025.xls',
            ],
            [
                'subsidebar' => 'PERKEBUNAN',
                'nama_judul' => 'Produksi Perkebunan Rakyat Menurut Jenis Tanaman di Kabupaten Sukabumi',
                'slug' => 'produksi-perkebunan-rakyat-menurut-jenis-tanaman-di-kabupaten-sukabumi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Produksi Perkebunan Rakyat Menurut Jenis Tanaman di Kabupaten Sukabumi 2025.xls',
            ],
            [
                'subsidebar' => 'PETERNAKAN',
                'nama_judul' => 'Dinamika Populasi Ternak Kabupaten Sukabumi (Ekor)',
                'slug' => 'dinamika-populasi-ternak-kabupaten-sukabumi-ekor',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Dinamika Populasi Ternak Kabupaten Sukabumi (Ekor)2025.xls',
            ],
            [
                'subsidebar' => 'PETERNAKAN',
                'nama_judul' => 'Produksi Daging Menurut Jenis Ternak di Kabupaten Sukabumi',
                'slug' => 'produksi-daging-menurut-jenis-ternak-di-kabupaten-sukabumi',
                'tipe_baris' => 'custom',
                'nama_file_asli' => 'Produksi Daging Menurut Jenis Ternak di Kabupaten Sukabumi 2025.xls',
            ],
        ];

        // Cache subsidebar per slug supaya tidak query berulang di dalam loop.
        $subsidebarCache = [];

        foreach ($data as $urutan => $row) {
            $slugSubsidebar = Str::slug($row['subsidebar']);

            if (! array_key_exists($slugSubsidebar, $subsidebarCache)) {
                $subsidebarCache[$slugSubsidebar] = Subsidebar::where('slug', $slugSubsidebar)->first();
            }

            $subsidebar = $subsidebarCache[$slugSubsidebar];

            if (! $subsidebar) {
                continue;
            }

            Indikator::updateOrCreate(
                ['slug' => $row['slug']],
                [
                    'subsidebar_id' => $subsidebar->id,
                    'nama_judul' => $row['nama_judul'],
                    'satuan' => null,
                    'tipe_baris' => $row['tipe_baris'],
                    'nama_file_asli' => $row['nama_file_asli'],
                    'urutan' => $urutan + 1,
                ]
            );
        }
    }
}
